### ISSUE TITLE
No Unity Project

### ISSUE THREAD

**Issue by TheCyberCoder1** [TheCyberCoder1/Unity_Obstacle_Course#1]
My Unity project is very large and i am currently trying to find a way to upload it without any junk.

**Comment by arbusam** [comment]
If you pull the .gitignore to your local directory you can then `git commit` excluding all the junk. If you have already committed it without the .gitignore then you will have to do `git rm Library` and `git rm Logs` then commit and push.

**Comment by TheCyberCoder1** [comment]
Thank you, will do soon
